name: Reset File On Readme Change
on:
  push:
    paths:
      - 'README.md'

jobs:
  reset-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Reset File
        run: |
          echo -n "" > reset
          git add reset
          git commit -m "Reset file"
