name: Update Push Number
on:
  push:
    branches:
      - main

jobs:
  update-push-number:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Read current number
        id: read-number
        run: |
          number=$(cat push_number 2>/dev/null)
          if [[ -z $number ]]; then
            number=0
          fi
          echo "::set-output name=number::$number"

      - name: Increment number
        id: increment-number
        run: |
          current_number=$(echo "${{ steps.read-number.outputs.number }}")
          new_number=$((current_number + 1))
          echo "::set-output name=new_number::$new_number"

      - name: Write new number to file
        run: |
          echo "${{ steps.increment-number.outputs.new_number }}" > push_number

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Update push number"
          git push
