name: Generate Output on Push
on:
  push:
    branches:
      - main

jobs:
  generate-output:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Output
        run: |
          echo "Ein Push wurde in das Repository durchgeführt!"
